- includes/mod_cen/clases/SubTipoInforme.php
- includes/mod_cen/clases/categoria.php
- includes/mod_cen/formularios/f_Delete_SubTipoInforme.php
- includes/mod_cen/formularios/f_Modif_SubTipoInforme.php
- includes/mod_cen/formularios/f_nuevoSubTipoInforme.php
- includes/mod_cen/informes/delete_subtipo_informe.php
- includes/mod_cen/informes/listarSubtipo.php
- includes/mod_cen/informes/nuevoSubTipoInforme.php
- includes/mod_cen/informes/update_subtipo_informe.php
te envio el codigo solicitado sobre subitpo. falta crear tabla y modificar menu de admin
> agregue subtipo completo

- includes/mod_cen/login_f.php
Envio la modificación del formulario login.
> Actualizacion de apariencia formulario login

- includes/mod_cen/clases/vicedirector.php
- includes/mod_cen/formularios/f_BajaViceDirector.php
- includes/mod_cen/formularios/f_Modif_ViceDirector.php
- includes/mod_cen/personas/listado_vicedirector.php
- includes/mod_cen/personas/vicedirector_borrar.php
- includes/mod_cen/personas/vicedirector_editar.php
- includes/mod_men/admin.php
- modulos/centro.php
>  avance en vicedirector editar-borrar

- includes/mod_cen/clases/vicedirector.php
> modificaciones en pdo de editar y eliminar

- includes/mod_cen/clases/vicedirector.php
- includes/mod_cen/personas/listado_vicedirector.php
- test/carga_imagenes/f_cargaImagen.php
> pdo vicedirector y test

- includes/mod_cen/informes/email_script.php
> modificaciones de script mail

- includes/mod_cen/informes/email_script.php
mail para att y coordinador pmi
> modificacion script mail para att

- includes/mod_cen/clases/respuesta.php
- includes/mod_cen/informes/email_script_resp.php
> nuevo metodo de respuesta

- includes/mod_cen/formularios/js/form_personaf.js
- includes/mod_cen/formularios/personaf.php
Se actualizo la validacion completa del formulario para actualizar perfil
> Validacion completa de formulario actualizar perfil

- .gitignore
- includes/mod_cen/documentos/etj.php
- includes/mod_cen/documentos/panel.js
- includes/mod_men/etj.php
- includes/mod_men/ett.php
se crea menu documentos para usuarios ETT y ETJ
> Se crea nuevo menú documentos

- includes/mod_cen/informes/email_script_resp.php
> mail de respuesta terminado

- includes/mod_cen/clases/PermisoCategoriaDoc.php
> creacion de clase nueva

- includes/mod_cen/clases/CategoriaDoc.php
- includes/mod_cen/clases/Documento.php
- includes/mod_cen/clases/PermisoDoc.php
> clases nuevas

- includes/mod_cen/clases/CategoriaDoc.php
- includes/mod_cen/clases/PermisoCategoriaDoc.php
- includes/mod_cen/formularios/f_documento.php
- includes/mod_cen/formularios/f_nueva_categoria_doc.php
- includes/mod_cen/informes/nuevaCategoriaDoc.php
- includes/mod_men/admin.php
- modulos/centro.php
> script y formulario nuevos

- includes/mod_cen/documentos/att.php
- includes/mod_cen/documentos/coordinador-conectar.php
- includes/mod_cen/documentos/coordinador-pmi.php
- includes/mod_cen/documentos/etj.php
- includes/mod_cen/documentos/ett.php
- includes/mod_cen/documentos/panelportada.js
- includes/mod_cen/portada/att.php
- includes/mod_cen/portada/coordinador.php
- includes/mod_cen/portada/coordinadorpmi.php
- includes/mod_cen/portada/etj.php
- includes/mod_cen/portada/ett.php
se agrega  el menu documentos en portadas etj-ett-att-coordinador conectar y coordinador pmi
> Se actualizan portadas

- includes/mod_cen/clases/CategoriaDoc.php
- includes/mod_cen/clases/Documento.php
- includes/mod_cen/clases/PermisoCategoriaDoc.php
- includes/mod_cen/clases/PermisoDoc.php
- includes/mod_cen/documentos/listarDocumentos.php
- includes/mod_cen/documentos/modificarDocumento.php
- includes/mod_cen/documentos/nuevo_documento.php
- includes/mod_cen/formularios/f_Modif_documento.php
- includes/mod_cen/formularios/f_modif_categoria_doc.php
- includes/mod_cen/informes/listarCategoriaDoc.php
- includes/mod_cen/informes/modificarCategoriaDoc.php
- includes/mod_cen/informes/nuevaCategoriaDoc.php
- includes/mod_cen/js/permisos.js
- includes/mod_men/admin.php
- modulos/centro.php
categoriaDoc y Documentos terminado
> categoriaDoc y Documentos terminado

- includes/mod_cen/estadisticas/estadisPermer.php
se corrige tamaño de grafico para vista celular
> Correccion de tamaño de graficos

- includes/mod_cen/clases/Documento.php
- includes/mod_cen/documentos/modificarDocumento.php
- includes/mod_cen/documentos/nuevo_documento.php
documento y modif de documento con campos referenteId y tipo
> nuevo documento y modif documento con  campos  referenteId y tipo

- includes/mod_cen/formularios/js/mod_doc.js
Correccion de campo adjuntar archivo no obligatorio
> correccion2 validacion modificar documento

- includes/mod_cen/informes/email_script.php
- includes/mod_cen/informes/email_script_resp.php
> modificaciones

- includes/mod_cen/formularios/js/f_nuevoDoc.js
- includes/mod_cen/formularios/js/mod_doc.js
modificacion de archivo .js para campo descripcion en formularios crear y modificar documentos
> modificacion de archivo .js

- includes/mod_cen/clases/informe.php
- includes/mod_cen/portada/ett.php
agregue este metodo que es una copia del buscar para no tocar el metodo buscar original.
> agregue metodo buscar escuelaDelETT en informe

- includes/mod_cen/clases/informe.php
- includes/mod_cen/portada/ett.php
metodo corregido en buscarEscuelasDelETT
> metodo corregido de buscar en informe de ett

- includes/mod_cen/clases/Documento.php
- includes/mod_cen/documentos/nuevo_documento.php
envio de mail para documento nuevo
> envio de mail para documento nuevo

- includes/mod_cen/escuelas/agregarEscuelas.php
- includes/mod_cen/formularios/f_NuevaEscuela.php
- includes/mod_men/admin.php
- modulos/centro.php
script para agregar una nueva escuela
> script agregar nueva escuela

- includes/mod_cen/clases/escuela.php
- includes/mod_cen/escuelas/agregarEscuelas.php
Script agregar escuela nueva funcionando
> Script agregar escuela nueva funcionando

- includes/mod_cen/clases/Dispositivo.php
- includes/mod_cen/clases/login.php
- includes/mod_cen/dispositivoAcceso.php
- includes/mod_cen/estadisticas/estadisticaDispositivo.php
- includes/mod_cen/estadisticas/estadisticaDispositivo1.php
- includes/mod_men/admin.php
- modulos/centro.php
> estadistica de dispositivos

- includes/mod_cen/estadisticas/estadisticaDispositivo1.php
> estadistica modificado

- includes/mod_cen/clases/Dispositivo.php
- includes/mod_cen/estadisticas/estadisticaDispositivo1.php
> modificado totales

- includes/mod_cen/escuelas/escuelaDatosDirectivo.php
- includes/mod_cen/estadisticas/estadisticaDispositivo1.php
- includes/mod_cen/referentes/referente_ett.php
- modulos/centro.php
modificacion de estadisticas en supervisores de secundaria y trabajo inicial de directores
>  modificacion en estadistica y otros

- includes/mod_cen/cargarAutoridad.Cuerpo.php
- includes/mod_cen/escuelas/escuelaDatosDirectivo.php
- includes/mod_cen/referentes/referente_ett.php
- includes/mod_cen/registrarAutoridad.php
script terminado de listado de directores con botones de modificar y cargar
> terminado script directores

- includes/mod_cen/login_f.php
- includes/mod_cen/portada/coordinadorEducacionFisica.php
- includes/mod_cen/portada/referenteEducacionFisica.php
- includes/mod_men/coordinadorEducacionFisica.php
- includes/mod_men/referenteEducacionFisica.php
- modulos/menu.php
este es un avance del referente para ed fisica
> avance de referente ed fisica

- includes/mod_cen/escuelas/escuela_ver_EF.php
- includes/mod_men/coordinadorEducacionFisica.php
- includes/mod_men/referenteEducacionFisica.php
- modulos/centro.php
> avance en ed fisica

- includes/mod_cen/escuelas/escuela_ver_EF.php
- includes/mod_cen/portada/referenteEducacionFisica.php
- modulos/centro.php
> avance en ed fisica2

- includes/mod_cen/escuelas/escuela_ver_EF.php
Escuelas educacion fisica en proceso
> Escuelas educacion fisica

- includes/mod_cen/clases/EdFisicaxEscuela.php
- includes/mod_cen/edFisica/nuevoProfe.php
- modulos/centro.php
nuevos archivos para ed fisica
> nuevos archivos para ed fisica

- includes/mod_cen/clases/ProfesoresEF.php
- includes/mod_cen/edFisica/nuevoProfe.php
- includes/mod_cen/escuelas/escuelaEdFisica.php
- includes/mod_cen/escuelas/js/escuelaEF.js
- includes/mod_cen/formularios/f_HorarioNuevoProfesorEF.php
- modulos/centro.php
> avance ed fisica

- includes/mod_cen/clases/EdFisicaxEscuela.php
- includes/mod_cen/clases/ProfeEdFisicaxCurso.php
- includes/mod_cen/clases/ProfeEdFisicaxEscuela.php
- includes/mod_cen/clases/ProfesoresEF.php
- includes/mod_cen/clases/ajax/profeEdFisica.php
- includes/mod_cen/escuelas/escuelaEdFisica.php
- includes/mod_cen/escuelas/js/escuelaEF.js
> avance para ed fisica

- includes/mod_cen/clases/ProfeEdFisicaxEscuela.php
- includes/mod_cen/clases/ajax/profeEdFisica.php
- includes/mod_cen/escuelas/escuelaEdFisica.php
- includes/mod_cen/escuelas/escuela_ver_EF.php
- includes/mod_cen/escuelas/js/escuelaEF.js
- includes/mod_cen/formularios/buscadorEdFisica.php
> avance nuevo profe ed fisica

- includes/mod_cen/clases/ProfeEdFisicaxEscuela.php
- includes/mod_cen/escuelas/escuela_ver_EF.php
en proceso: correccion boton nuevo curso,problema en Id
> Listado de profesores por escuela terminado

- includes/mod_cen/clases/ProfeEdFisicaxCurso.php
- includes/mod_cen/clases/ProfeEdFisicaxEscuela.php
- includes/mod_cen/clases/ajax/profeEdFisica.php
- includes/mod_cen/escuelas/escuelaEdFisica.php
- includes/mod_cen/escuelas/js/escuelaEF.js
- includes/mod_cen/formularios/f_HorarioNuevoCursoProf.php
> modificacion ed fisica

- includes/mod_cen/clases/ajax/profeEdFisica.php
- includes/mod_cen/edFisica/js/botonesEF.js
- includes/mod_cen/escuelas/escuelaEdFisica.php
- includes/mod_cen/escuelas/escuela_ver_EF.php
- includes/mod_cen/escuelas/js/escuelaEF.js
- includes/mod_cen/formularios/f_HorarioNuevoProfesorEF.php
modificaciones varias Ed Fisica
> modificaciones varias

- includes/mod_cen/edFisica/js/botonesEF.js
- includes/mod_cen/escuelas/escuela_ver_EF.php
> ultimas modificaciones

- includes/mod_cen/escuelas/escuela_ver_EF.php
- includes/mod_cen/formularios/f_HorarioNuevoProfesorEF.php
- includes/mod_cen/referentes/referente_verEF.php
> modificaciones finales

- includes/mod_cen/clases/Autoridades.php
- includes/mod_cen/clases/TipoAutoridades.php
- includes/mod_cen/escuelas/listarAutoridades.php
- includes/mod_cen/escuelas/listarTipoAutoridades.php
- includes/mod_cen/escuelas/nuevaAutoridad.php
- includes/mod_cen/escuelas/nuevoTipoAutoridades.php
- includes/mod_cen/escuelas/updateTipoAutoridades.php
- includes/mod_cen/formularios/f_Modif_TipoAutoridades.php
- includes/mod_cen/formularios/f_nuevaAutoridad.php
- includes/mod_cen/formularios/f_nuevoTipoAutoridades.php
- includes/mod_men/admin.php
- modulos/centro.php
archivos creados para supervisores
> archivos creados para supervisores

- includes/mod_cen/edFisica/js/botonesEF.js
- includes/mod_cen/escuelas/misEscuelasSuper.php
- includes/mod_men/admin.php
- modulos/centro.php
> MIs escuelas supervisor

- includes/mod_cen/escuelas/listarAutoridades.php
- includes/mod_cen/escuelas/listarTipoAutoridades.php
- includes/mod_cen/escuelas/nuevaAutoridad.php
- includes/mod_cen/escuelas/nuevoTipoAutoridades.php
- includes/mod_cen/escuelas/updateTipoAutoridades.php
- includes/mod_cen/formularios/f_Modif_TipoAutoridades.php
- includes/mod_cen/formularios/f_nuevaAutoridad.php
- includes/mod_cen/formularios/f_nuevoTipoAutoridades.php
- modulos/centro.php
> archivos modificados

- includes/mod_cen/admin/escuelaAsignarSEP.php
- includes/mod_cen/admin/escuelaAsignarSH.php
- includes/mod_cen/admin/escuelaAsignarSI.php
- includes/mod_cen/admin/escuelaAsignarSNP.php
- includes/mod_cen/admin/escuelaAsignarSP.php
- includes/mod_cen/admin/escuelaAsignarSR.php
- includes/mod_cen/clases/maestro.php
- includes/mod_cen/clases/referente.php
- includes/mod_men/admin.php
- modulos/centro.php
> asignar supervisores varios

- includes/mod_cen/admin/escuela_asignar_admin_Ett.php
- includes/mod_cen/clases/Autoridades.php
- includes/mod_cen/clases/EscuelaReferentes.php
- includes/mod_cen/clases/escuela.php
- includes/mod_cen/clases/maestro.php
- includes/mod_men/admin.php
- modulos/centro.php
> asignar ETT nuevo

- includes/mod_cen/escuelas/misEscuelasSuper.php
> modificacion misEscuelas

- includes/mod_cen/admin/escuela_asignar_admin_Etj.php
- includes/mod_cen/clases/Autoridades.php
- includes/mod_cen/clases/escuela.php
- includes/mod_cen/clases/maestro.php
- includes/mod_cen/clases/referente.php
- includes/mod_men/admin.php
- modulos/centro.php
> asignar escuelas varios

- includes/mod_cen/clases/Autoridades.php
- includes/mod_cen/clases/escuela.php
- includes/mod_men/admin.php
asignacion escuelas supervisores primaria
> asignacion escuelas supervisores

- includes/mod_cen/informes/email_script.php
- includes/mod_cen/informes/email_script_resp.php
script enviar mail de informe  y respuesta modificado
> script enviar mail modificado

- includes/mod_cen/escuelas/escuela_ver_PL.php
- includes/mod_cen/formularios/buscadorPlanLectura.php
- includes/mod_cen/informes/email_script.php
- includes/mod_cen/informes/list_view_report.php
- includes/mod_cen/login_f.php
- includes/mod_cen/portada/coordinadorPlanLectura.php
- includes/mod_cen/portada/ettPlanLectura.php
- includes/mod_men/coordinadorPlanLectura.php
- includes/mod_men/ettPlanLectura.php
- modulos/centro.php
- modulos/menu.php
> Plan de Lectura Final

- includes/mod_cen/estadisticas/estadisticaDispositivo1.php
plan lectura estadistica por acceso de dispositivo
> plan lectura estadistica

- includes/mod_cen/informes/calendarByMonth.php
calendario visitas ETT para portada ETJ
> calendario visitas ETT

- includes/mod_cen/informes/calendarByMonth.php
otras modificaciones calendario ETT
> calendario ett

- includes/mod_men/etj.php
> asignar ETT para portada ETJ

- includes/mod_cen/clases/EscuelaReferentes.php
- includes/mod_cen/informes/calendarByMonth.php
- includes/mod_cen/portada/calendarioEtt.php
calendario ett modificado para escuelaReferentes
> calendario ett modificado

- includes/mod_cen/clases/ajax/ajaxInformeNuevo.php
- includes/mod_cen/clases/ajax/ajaxRespuesta.php
- includes/mod_cen/escuelas/escuela_ver_etj.php
- includes/mod_cen/escuelas/escuela_ver_ett.php
email y buscador de escuela que lee datos de la tabla escuelaReferentes
> email y buscador de escuela

- includes/mod_cen/clases/ajax/ajaxInformeNuevo.php
- includes/mod_cen/informes/email_script.php
modificaciones para email informes
> modificaciones para email

- includes/mod_cen/clases/ajax/ajaxInformeNuevo.php
- includes/mod_cen/informes/email_script.php
- includes/mod_cen/informes/email_scriptAjax.php
> mail nuevo para informes

- includes/mod_cen/clases/ajax/ajaxRespuesta.php
- includes/mod_cen/informes/email_script.php
- includes/mod_cen/informes/email_scriptAjax.php
- includes/mod_cen/informes/email_scriptAjaxResp.php
- includes/mod_cen/informes/email_script_resp.php
> script respuesta informe

- includes/mod_cen/clases/ajax/personaEditado.php
- includes/mod_cen/formularios/js/form_personaf2.js
- includes/mod_cen/formularios/js/perfilEditar.js
- includes/mod_cen/formularios/personaf.php
> archivos foto perfil

- includes/mod_cen/escuelas/js/jsEscuelaVerEtj.js
archivos para buscador de escuela etj
> archivos para buscador de escuela etj

- includes/mod_cen/escuelas/escuela_ver_ett.php
escuela ver ett modificado para listar directivos y supervisores de la tabla autoridades
> escuela ver ett modificado

- includes/mod_cen/clases/EscuelaReferentes.php
- includes/mod_cen/escuelas/escuela_ett_etj.php
- includes/mod_cen/referentes/referente_ett_todos.php
- includes/mod_cen/rti/rti_ett_etj.php
ver todos los ett en la portada etj
> ver todos los ett

- includes/mod_cen/clases/ajax/ajaxInforme.php
- includes/mod_cen/clases/cadenas.php
script para quitar acentos del titulo del informe desde archivo ajax.
> script para acentos del titulo

- includes/mod_cen/clases/ajax/ajaxPredio.php
- includes/mod_cen/escuelas/escuela_ver_ett.php
- includes/mod_cen/escuelas/js/agregaMisEscuelasSupervisor.js
- includes/mod_cen/escuelas/js/ajax.js
lista de predios compartidos para buscador de escuelas tradicional
> lista de predios compartidos

- includes/mod_cen/escuelas/escuela_ver_ett.php
> Detalle en buscador

- includes/mod_cen/informes/email_script.php
- includes/mod_cen/informes/email_scriptAjax.php
modificacion de mail par pnce alta de manera que se envie mail a luis castro
> modificacion de mail par pnce alta

- includes/mod_cen/informes/email_script.php
modificacion para script email modificado
> script email modificado
